name: Build the extension

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest
      - name: Install dependencies
        run: npm ci
      - name: Package extension into a .vsix file
        id: package
        run: npm run package
      - name: Upload artifact on github
        uses: actions/upload-artifact@v3
        with:
          name: Extension Package
          path: "*.vsix"
